name: "FTP Deployment to Azure App Service"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # - name: Install dependencies
      #   run: npm install 

      - name: Export the application
        run: npm run export  # This will generate the static files in the /out folder

      - name: List contents of the out folder
        run: ls -R out  # This will list the contents of the out folder to verify

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: out  # Path to the Next.js exported output folder

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # - name: Download build artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: build-artifacts

      - name: Deploy to Azure using FTPS
        env:
          FTP_HOST: ${{ secrets.AZURE_FTP_HOST }}
          FTP_USERNAME: ${{ secrets.AZURE_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.AZURE_FTP_PASSWORD }}
        run: |
          # Upload all files from the out folder to Azure's wwwroot folder
          curl -T "./out/*" --ftp-create-dirs -u $FTP_USERNAME:$FTP_PASSWORD ftps://$FTP_HOST/site/wwwroot/
